// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/opaque.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpaqueSearch_RegisterKey_FullMethodName         = "/opaque.v1.OpaqueSearch/RegisterKey"
	OpaqueSearch_GetPlanes_FullMethodName           = "/opaque.v1.OpaqueSearch/GetPlanes"
	OpaqueSearch_GetCandidates_FullMethodName       = "/opaque.v1.OpaqueSearch/GetCandidates"
	OpaqueSearch_ComputeScores_FullMethodName       = "/opaque.v1.OpaqueSearch/ComputeScores"
	OpaqueSearch_ComputeScoresStream_FullMethodName = "/opaque.v1.OpaqueSearch/ComputeScoresStream"
	OpaqueSearch_Search_FullMethodName              = "/opaque.v1.OpaqueSearch/Search"
	OpaqueSearch_HealthCheck_FullMethodName         = "/opaque.v1.OpaqueSearch/HealthCheck"
)

// OpaqueSearchClient is the client API for OpaqueSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OpaqueSearch is the main service for privacy-preserving vector search.
type OpaqueSearchClient interface {
	// RegisterKey registers a client's public key and creates a session.
	RegisterKey(ctx context.Context, in *RegisterKeyRequest, opts ...grpc.CallOption) (*RegisterKeyResponse, error)
	// GetPlanes retrieves the LSH hyperplanes for client-side hashing.
	GetPlanes(ctx context.Context, in *GetPlanesRequest, opts ...grpc.CallOption) (*GetPlanesResponse, error)
	// GetCandidates performs LSH lookup to find candidate vectors.
	GetCandidates(ctx context.Context, in *CandidateRequest, opts ...grpc.CallOption) (*CandidateResponse, error)
	// ComputeScores computes encrypted similarity scores for candidates.
	ComputeScores(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	// ComputeScoresStream streams encrypted scores one at a time (for large responses).
	ComputeScoresStream(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScoreChunk], error)
	// Search performs the complete search flow in one call (convenience method).
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// HealthCheck checks service health.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type opaqueSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewOpaqueSearchClient(cc grpc.ClientConnInterface) OpaqueSearchClient {
	return &opaqueSearchClient{cc}
}

func (c *opaqueSearchClient) RegisterKey(ctx context.Context, in *RegisterKeyRequest, opts ...grpc.CallOption) (*RegisterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterKeyResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_RegisterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opaqueSearchClient) GetPlanes(ctx context.Context, in *GetPlanesRequest, opts ...grpc.CallOption) (*GetPlanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanesResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_GetPlanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opaqueSearchClient) GetCandidates(ctx context.Context, in *CandidateRequest, opts ...grpc.CallOption) (*CandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CandidateResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_GetCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opaqueSearchClient) ComputeScores(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_ComputeScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opaqueSearchClient) ComputeScoresStream(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScoreChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpaqueSearch_ServiceDesc.Streams[0], OpaqueSearch_ComputeScoresStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScoreRequest, ScoreChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpaqueSearch_ComputeScoresStreamClient = grpc.ServerStreamingClient[ScoreChunk]

func (c *opaqueSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opaqueSearchClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OpaqueSearch_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpaqueSearchServer is the server API for OpaqueSearch service.
// All implementations must embed UnimplementedOpaqueSearchServer
// for forward compatibility.
//
// OpaqueSearch is the main service for privacy-preserving vector search.
type OpaqueSearchServer interface {
	// RegisterKey registers a client's public key and creates a session.
	RegisterKey(context.Context, *RegisterKeyRequest) (*RegisterKeyResponse, error)
	// GetPlanes retrieves the LSH hyperplanes for client-side hashing.
	GetPlanes(context.Context, *GetPlanesRequest) (*GetPlanesResponse, error)
	// GetCandidates performs LSH lookup to find candidate vectors.
	GetCandidates(context.Context, *CandidateRequest) (*CandidateResponse, error)
	// ComputeScores computes encrypted similarity scores for candidates.
	ComputeScores(context.Context, *ScoreRequest) (*ScoreResponse, error)
	// ComputeScoresStream streams encrypted scores one at a time (for large responses).
	ComputeScoresStream(*ScoreRequest, grpc.ServerStreamingServer[ScoreChunk]) error
	// Search performs the complete search flow in one call (convenience method).
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// HealthCheck checks service health.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedOpaqueSearchServer()
}

// UnimplementedOpaqueSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpaqueSearchServer struct{}

func (UnimplementedOpaqueSearchServer) RegisterKey(context.Context, *RegisterKeyRequest) (*RegisterKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterKey not implemented")
}
func (UnimplementedOpaqueSearchServer) GetPlanes(context.Context, *GetPlanesRequest) (*GetPlanesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanes not implemented")
}
func (UnimplementedOpaqueSearchServer) GetCandidates(context.Context, *CandidateRequest) (*CandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidates not implemented")
}
func (UnimplementedOpaqueSearchServer) ComputeScores(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeScores not implemented")
}
func (UnimplementedOpaqueSearchServer) ComputeScoresStream(*ScoreRequest, grpc.ServerStreamingServer[ScoreChunk]) error {
	return status.Error(codes.Unimplemented, "method ComputeScoresStream not implemented")
}
func (UnimplementedOpaqueSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedOpaqueSearchServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOpaqueSearchServer) mustEmbedUnimplementedOpaqueSearchServer() {}
func (UnimplementedOpaqueSearchServer) testEmbeddedByValue()                      {}

// UnsafeOpaqueSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpaqueSearchServer will
// result in compilation errors.
type UnsafeOpaqueSearchServer interface {
	mustEmbedUnimplementedOpaqueSearchServer()
}

func RegisterOpaqueSearchServer(s grpc.ServiceRegistrar, srv OpaqueSearchServer) {
	// If the following call panics, it indicates UnimplementedOpaqueSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpaqueSearch_ServiceDesc, srv)
}

func _OpaqueSearch_RegisterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).RegisterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_RegisterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).RegisterKey(ctx, req.(*RegisterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpaqueSearch_GetPlanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).GetPlanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_GetPlanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).GetPlanes(ctx, req.(*GetPlanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpaqueSearch_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_GetCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).GetCandidates(ctx, req.(*CandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpaqueSearch_ComputeScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).ComputeScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_ComputeScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).ComputeScores(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpaqueSearch_ComputeScoresStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OpaqueSearchServer).ComputeScoresStream(m, &grpc.GenericServerStream[ScoreRequest, ScoreChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpaqueSearch_ComputeScoresStreamServer = grpc.ServerStreamingServer[ScoreChunk]

func _OpaqueSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpaqueSearch_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpaqueSearchServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpaqueSearch_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpaqueSearchServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpaqueSearch_ServiceDesc is the grpc.ServiceDesc for OpaqueSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpaqueSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opaque.v1.OpaqueSearch",
	HandlerType: (*OpaqueSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterKey",
			Handler:    _OpaqueSearch_RegisterKey_Handler,
		},
		{
			MethodName: "GetPlanes",
			Handler:    _OpaqueSearch_GetPlanes_Handler,
		},
		{
			MethodName: "GetCandidates",
			Handler:    _OpaqueSearch_GetCandidates_Handler,
		},
		{
			MethodName: "ComputeScores",
			Handler:    _OpaqueSearch_ComputeScores_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _OpaqueSearch_Search_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OpaqueSearch_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ComputeScoresStream",
			Handler:       _OpaqueSearch_ComputeScoresStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/opaque.proto",
}
