// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/opaque.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_opaque_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_api_proto_opaque_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{12, 0}
}

// RegisterKeyRequest contains the client's public key for session creation.
type RegisterKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized public key (Lattigo format)
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Requested session TTL in seconds (server may enforce max)
	SessionTtlSeconds int32 `protobuf:"varint,2,opt,name=session_ttl_seconds,json=sessionTtlSeconds,proto3" json:"session_ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterKeyRequest) Reset() {
	*x = RegisterKeyRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyRequest) ProtoMessage() {}

func (x *RegisterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterKeyRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterKeyRequest) GetSessionTtlSeconds() int32 {
	if x != nil {
		return x.SessionTtlSeconds
	}
	return 0
}

// RegisterKeyResponse returns the session ID for subsequent requests.
type RegisterKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session identifier
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Actual TTL granted (may be less than requested)
	SessionTtlSeconds int32 `protobuf:"varint,2,opt,name=session_ttl_seconds,json=sessionTtlSeconds,proto3" json:"session_ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterKeyResponse) Reset() {
	*x = RegisterKeyResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyResponse) ProtoMessage() {}

func (x *RegisterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyResponse.ProtoReflect.Descriptor instead.
func (*RegisterKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterKeyResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterKeyResponse) GetSessionTtlSeconds() int32 {
	if x != nil {
		return x.SessionTtlSeconds
	}
	return 0
}

// GetPlanesRequest requests the LSH hyperplanes.
type GetPlanesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanesRequest) Reset() {
	*x = GetPlanesRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanesRequest) ProtoMessage() {}

func (x *GetPlanesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanesRequest.ProtoReflect.Descriptor instead.
func (*GetPlanesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlanesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetPlanesResponse contains the LSH hyperplanes for client-side hashing.
type GetPlanesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flattened hyperplanes (num_planes * dimension floats)
	Planes []float64 `protobuf:"fixed64,1,rep,packed,name=planes,proto3" json:"planes,omitempty"`
	// Number of planes (hash bits)
	NumPlanes int32 `protobuf:"varint,2,opt,name=num_planes,json=numPlanes,proto3" json:"num_planes,omitempty"`
	// Vector dimension
	Dimension     int32 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanesResponse) Reset() {
	*x = GetPlanesResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanesResponse) ProtoMessage() {}

func (x *GetPlanesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanesResponse.ProtoReflect.Descriptor instead.
func (*GetPlanesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanesResponse) GetPlanes() []float64 {
	if x != nil {
		return x.Planes
	}
	return nil
}

func (x *GetPlanesResponse) GetNumPlanes() int32 {
	if x != nil {
		return x.NumPlanes
	}
	return 0
}

func (x *GetPlanesResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

// CandidateRequest requests candidate vectors by LSH hash.
type CandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// LSH hash computed by client
	LshHash []byte `protobuf:"bytes,2,opt,name=lsh_hash,json=lshHash,proto3" json:"lsh_hash,omitempty"`
	// Maximum number of candidates to return
	NumCandidates int32 `protobuf:"varint,3,opt,name=num_candidates,json=numCandidates,proto3" json:"num_candidates,omitempty"`
	// Use multi-probe LSH (check neighboring buckets)
	MultiProbe bool `protobuf:"varint,4,opt,name=multi_probe,json=multiProbe,proto3" json:"multi_probe,omitempty"`
	// Number of probes for multi-probe LSH
	NumProbes     int32 `protobuf:"varint,5,opt,name=num_probes,json=numProbes,proto3" json:"num_probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateRequest) Reset() {
	*x = CandidateRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateRequest) ProtoMessage() {}

func (x *CandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateRequest.ProtoReflect.Descriptor instead.
func (*CandidateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CandidateRequest) GetLshHash() []byte {
	if x != nil {
		return x.LshHash
	}
	return nil
}

func (x *CandidateRequest) GetNumCandidates() int32 {
	if x != nil {
		return x.NumCandidates
	}
	return 0
}

func (x *CandidateRequest) GetMultiProbe() bool {
	if x != nil {
		return x.MultiProbe
	}
	return false
}

func (x *CandidateRequest) GetNumProbes() int32 {
	if x != nil {
		return x.NumProbes
	}
	return 0
}

// CandidateResponse contains candidate vector IDs.
type CandidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate vector IDs
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// Hamming distances to query hash
	Distances     []int32 `protobuf:"varint,2,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse) Reset() {
	*x = CandidateResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse) ProtoMessage() {}

func (x *CandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse.ProtoReflect.Descriptor instead.
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{5}
}

func (x *CandidateResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *CandidateResponse) GetDistances() []int32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

// ScoreRequest requests encrypted similarity scores.
type ScoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Encrypted query vector (serialized ciphertext)
	EncryptedQuery []byte `protobuf:"bytes,2,opt,name=encrypted_query,json=encryptedQuery,proto3" json:"encrypted_query,omitempty"`
	// Candidate IDs to score
	CandidateIds  []string `protobuf:"bytes,3,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScoreRequest) GetEncryptedQuery() []byte {
	if x != nil {
		return x.EncryptedQuery
	}
	return nil
}

func (x *ScoreRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

// ScoreResponse contains encrypted similarity scores.
type ScoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted scores (serialized ciphertexts)
	EncryptedScores [][]byte `protobuf:"bytes,1,rep,name=encrypted_scores,json=encryptedScores,proto3" json:"encrypted_scores,omitempty"`
	// Corresponding IDs (same order as scores)
	Ids           []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{7}
}

func (x *ScoreResponse) GetEncryptedScores() [][]byte {
	if x != nil {
		return x.EncryptedScores
	}
	return nil
}

func (x *ScoreResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// ScoreChunk is a single encrypted score for streaming.
type ScoreChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vector ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Encrypted score (serialized ciphertext)
	EncryptedScore []byte `protobuf:"bytes,2,opt,name=encrypted_score,json=encryptedScore,proto3" json:"encrypted_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScoreChunk) Reset() {
	*x = ScoreChunk{}
	mi := &file_api_proto_opaque_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreChunk) ProtoMessage() {}

func (x *ScoreChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreChunk.ProtoReflect.Descriptor instead.
func (*ScoreChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoreChunk) GetEncryptedScore() []byte {
	if x != nil {
		return x.EncryptedScore
	}
	return nil
}

// SearchRequest combines all steps into one request (convenience).
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// LSH hash computed by client
	LshHash []byte `protobuf:"bytes,2,opt,name=lsh_hash,json=lshHash,proto3" json:"lsh_hash,omitempty"`
	// Encrypted query vector
	EncryptedQuery []byte `protobuf:"bytes,3,opt,name=encrypted_query,json=encryptedQuery,proto3" json:"encrypted_query,omitempty"`
	// Maximum candidates to consider
	MaxCandidates int32 `protobuf:"varint,4,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	// Number of scores to compute and return
	TopN          int32 `protobuf:"varint,5,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchRequest) GetLshHash() []byte {
	if x != nil {
		return x.LshHash
	}
	return nil
}

func (x *SearchRequest) GetEncryptedQuery() []byte {
	if x != nil {
		return x.EncryptedQuery
	}
	return nil
}

func (x *SearchRequest) GetMaxCandidates() int32 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *SearchRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

// SearchResponse contains the complete search results.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted scores
	EncryptedScores [][]byte `protobuf:"bytes,1,rep,name=encrypted_scores,json=encryptedScores,proto3" json:"encrypted_scores,omitempty"`
	// Corresponding IDs
	Ids []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	// LSH distances (for debugging/analysis)
	LshDistances  []int32 `protobuf:"varint,3,rep,packed,name=lsh_distances,json=lshDistances,proto3" json:"lsh_distances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetEncryptedScores() [][]byte {
	if x != nil {
		return x.EncryptedScores
	}
	return nil
}

func (x *SearchResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SearchResponse) GetLshDistances() []int32 {
	if x != nil {
		return x.LshDistances
	}
	return nil
}

// HealthCheckRequest for service health check.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_opaque_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{11}
}

// HealthCheckResponse indicates service health.
type HealthCheckResponse struct {
	state  protoimpl.MessageState     `protogen:"open.v1"`
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=opaque.v1.HealthCheckResponse_Status" json:"status,omitempty"`
	// Additional info
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Number of active sessions
	ActiveSessions int64 `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	// Number of vectors in index
	VectorCount   int64 `protobuf:"varint,4,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_opaque_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_opaque_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_opaque_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthCheckResponse) GetVectorCount() int64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

var File_api_proto_opaque_proto protoreflect.FileDescriptor

const file_api_proto_opaque_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/opaque.proto\x12\topaque.v1\"c\n" +
	"\x12RegisterKeyRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12.\n" +
	"\x13session_ttl_seconds\x18\x02 \x01(\x05R\x11sessionTtlSeconds\"d\n" +
	"\x13RegisterKeyResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x13session_ttl_seconds\x18\x02 \x01(\x05R\x11sessionTtlSeconds\"1\n" +
	"\x10GetPlanesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"h\n" +
	"\x11GetPlanesResponse\x12\x16\n" +
	"\x06planes\x18\x01 \x03(\x01R\x06planes\x12\x1d\n" +
	"\n" +
	"num_planes\x18\x02 \x01(\x05R\tnumPlanes\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\x05R\tdimension\"\xb3\x01\n" +
	"\x10CandidateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\blsh_hash\x18\x02 \x01(\fR\alshHash\x12%\n" +
	"\x0enum_candidates\x18\x03 \x01(\x05R\rnumCandidates\x12\x1f\n" +
	"\vmulti_probe\x18\x04 \x01(\bR\n" +
	"multiProbe\x12\x1d\n" +
	"\n" +
	"num_probes\x18\x05 \x01(\x05R\tnumProbes\"C\n" +
	"\x11CandidateResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1c\n" +
	"\tdistances\x18\x02 \x03(\x05R\tdistances\"{\n" +
	"\fScoreRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fencrypted_query\x18\x02 \x01(\fR\x0eencryptedQuery\x12#\n" +
	"\rcandidate_ids\x18\x03 \x03(\tR\fcandidateIds\"L\n" +
	"\rScoreResponse\x12)\n" +
	"\x10encrypted_scores\x18\x01 \x03(\fR\x0fencryptedScores\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"E\n" +
	"\n" +
	"ScoreChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fencrypted_score\x18\x02 \x01(\fR\x0eencryptedScore\"\xae\x01\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\blsh_hash\x18\x02 \x01(\fR\alshHash\x12'\n" +
	"\x0fencrypted_query\x18\x03 \x01(\fR\x0eencryptedQuery\x12%\n" +
	"\x0emax_candidates\x18\x04 \x01(\x05R\rmaxCandidates\x12\x13\n" +
	"\x05top_n\x18\x05 \x01(\x05R\x04topN\"r\n" +
	"\x0eSearchResponse\x12)\n" +
	"\x10encrypted_scores\x18\x01 \x03(\fR\x0fencryptedScores\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12#\n" +
	"\rlsh_distances\x18\x03 \x03(\x05R\flshDistances\"\x14\n" +
	"\x12HealthCheckRequest\"\xef\x01\n" +
	"\x13HealthCheckResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.opaque.v1.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x03R\x0eactiveSessions\x12!\n" +
	"\fvector_count\x18\x04 \x01(\x03R\vvectorCount\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x8a\x04\n" +
	"\fOpaqueSearch\x12L\n" +
	"\vRegisterKey\x12\x1d.opaque.v1.RegisterKeyRequest\x1a\x1e.opaque.v1.RegisterKeyResponse\x12F\n" +
	"\tGetPlanes\x12\x1b.opaque.v1.GetPlanesRequest\x1a\x1c.opaque.v1.GetPlanesResponse\x12J\n" +
	"\rGetCandidates\x12\x1b.opaque.v1.CandidateRequest\x1a\x1c.opaque.v1.CandidateResponse\x12B\n" +
	"\rComputeScores\x12\x17.opaque.v1.ScoreRequest\x1a\x18.opaque.v1.ScoreResponse\x12G\n" +
	"\x13ComputeScoresStream\x12\x17.opaque.v1.ScoreRequest\x1a\x15.opaque.v1.ScoreChunk0\x01\x12=\n" +
	"\x06Search\x12\x18.opaque.v1.SearchRequest\x1a\x19.opaque.v1.SearchResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.opaque.v1.HealthCheckRequest\x1a\x1e.opaque.v1.HealthCheckResponseB-Z+github.com/opaque/opaque/go/api/proto;protob\x06proto3"

var (
	file_api_proto_opaque_proto_rawDescOnce sync.Once
	file_api_proto_opaque_proto_rawDescData []byte
)

func file_api_proto_opaque_proto_rawDescGZIP() []byte {
	file_api_proto_opaque_proto_rawDescOnce.Do(func() {
		file_api_proto_opaque_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_opaque_proto_rawDesc), len(file_api_proto_opaque_proto_rawDesc)))
	})
	return file_api_proto_opaque_proto_rawDescData
}

var file_api_proto_opaque_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_opaque_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_opaque_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: opaque.v1.HealthCheckResponse.Status
	(*RegisterKeyRequest)(nil),      // 1: opaque.v1.RegisterKeyRequest
	(*RegisterKeyResponse)(nil),     // 2: opaque.v1.RegisterKeyResponse
	(*GetPlanesRequest)(nil),        // 3: opaque.v1.GetPlanesRequest
	(*GetPlanesResponse)(nil),       // 4: opaque.v1.GetPlanesResponse
	(*CandidateRequest)(nil),        // 5: opaque.v1.CandidateRequest
	(*CandidateResponse)(nil),       // 6: opaque.v1.CandidateResponse
	(*ScoreRequest)(nil),            // 7: opaque.v1.ScoreRequest
	(*ScoreResponse)(nil),           // 8: opaque.v1.ScoreResponse
	(*ScoreChunk)(nil),              // 9: opaque.v1.ScoreChunk
	(*SearchRequest)(nil),           // 10: opaque.v1.SearchRequest
	(*SearchResponse)(nil),          // 11: opaque.v1.SearchResponse
	(*HealthCheckRequest)(nil),      // 12: opaque.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 13: opaque.v1.HealthCheckResponse
}
var file_api_proto_opaque_proto_depIdxs = []int32{
	0,  // 0: opaque.v1.HealthCheckResponse.status:type_name -> opaque.v1.HealthCheckResponse.Status
	1,  // 1: opaque.v1.OpaqueSearch.RegisterKey:input_type -> opaque.v1.RegisterKeyRequest
	3,  // 2: opaque.v1.OpaqueSearch.GetPlanes:input_type -> opaque.v1.GetPlanesRequest
	5,  // 3: opaque.v1.OpaqueSearch.GetCandidates:input_type -> opaque.v1.CandidateRequest
	7,  // 4: opaque.v1.OpaqueSearch.ComputeScores:input_type -> opaque.v1.ScoreRequest
	7,  // 5: opaque.v1.OpaqueSearch.ComputeScoresStream:input_type -> opaque.v1.ScoreRequest
	10, // 6: opaque.v1.OpaqueSearch.Search:input_type -> opaque.v1.SearchRequest
	12, // 7: opaque.v1.OpaqueSearch.HealthCheck:input_type -> opaque.v1.HealthCheckRequest
	2,  // 8: opaque.v1.OpaqueSearch.RegisterKey:output_type -> opaque.v1.RegisterKeyResponse
	4,  // 9: opaque.v1.OpaqueSearch.GetPlanes:output_type -> opaque.v1.GetPlanesResponse
	6,  // 10: opaque.v1.OpaqueSearch.GetCandidates:output_type -> opaque.v1.CandidateResponse
	8,  // 11: opaque.v1.OpaqueSearch.ComputeScores:output_type -> opaque.v1.ScoreResponse
	9,  // 12: opaque.v1.OpaqueSearch.ComputeScoresStream:output_type -> opaque.v1.ScoreChunk
	11, // 13: opaque.v1.OpaqueSearch.Search:output_type -> opaque.v1.SearchResponse
	13, // 14: opaque.v1.OpaqueSearch.HealthCheck:output_type -> opaque.v1.HealthCheckResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_opaque_proto_init() }
func file_api_proto_opaque_proto_init() {
	if File_api_proto_opaque_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_opaque_proto_rawDesc), len(file_api_proto_opaque_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_opaque_proto_goTypes,
		DependencyIndexes: file_api_proto_opaque_proto_depIdxs,
		EnumInfos:         file_api_proto_opaque_proto_enumTypes,
		MessageInfos:      file_api_proto_opaque_proto_msgTypes,
	}.Build()
	File_api_proto_opaque_proto = out.File
	file_api_proto_opaque_proto_goTypes = nil
	file_api_proto_opaque_proto_depIdxs = nil
}
