// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: gpuhe.proto

package gpuhe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUHEService_InitContext_FullMethodName      = "/opaque.gpu.v1.GPUHEService/InitContext"
	GPUHEService_RegisterEvalKeys_FullMethodName = "/opaque.gpu.v1.GPUHEService/RegisterEvalKeys"
	GPUHEService_BatchDotProduct_FullMethodName  = "/opaque.gpu.v1.GPUHEService/BatchDotProduct"
	GPUHEService_HealthCheck_FullMethodName      = "/opaque.gpu.v1.GPUHEService/HealthCheck"
)

// GPUHEServiceClient is the client API for GPUHEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GPUHEService offloads expensive HE operations to a GPU-accelerated server.
//
// Architecture:
//
//	Client (Go/Lattigo) handles: key generation, encryption, decryption
//	GPU Server handles: homomorphic multiply, rescale, Galois rotations, add
//
// The client sends evaluation keys once (RegisterEvalKeys), then sends
// encrypted queries for batch dot product computation. The server never
// has access to secret keys or decrypted data.
//
// Two modes:
//   - CPU stub: uses Lattigo-serialized bytes (bytes fields)
//   - GPU (HEonGPU): uses raw uint64 coefficients (RawPolynomial fields)
type GPUHEServiceClient interface {
	// InitContext creates an HEonGPU context with the given parameters and returns
	// the server's NTT primitive roots (ψ per prime). The client needs these roots
	// to convert evaluation key coefficients from Lattigo's NTT domain to HEonGPU's.
	// Must be called before RegisterEvalKeys.
	InitContext(ctx context.Context, in *InitContextRequest, opts ...grpc.CallOption) (*InitContextResponse, error)
	// RegisterEvalKeys sends evaluation keys (converted to server's NTT domain).
	RegisterEvalKeys(ctx context.Context, in *RegisterEvalKeysRequest, opts ...grpc.CallOption) (*RegisterEvalKeysResponse, error)
	// BatchDotProduct computes packed dot products via HE.
	BatchDotProduct(ctx context.Context, in *BatchDotProductRequest, opts ...grpc.CallOption) (*BatchDotProductResponse, error)
	// HealthCheck reports server status and backend type.
	HealthCheck(ctx context.Context, in *GPUHealthCheckRequest, opts ...grpc.CallOption) (*GPUHealthCheckResponse, error)
}

type gPUHEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUHEServiceClient(cc grpc.ClientConnInterface) GPUHEServiceClient {
	return &gPUHEServiceClient{cc}
}

func (c *gPUHEServiceClient) InitContext(ctx context.Context, in *InitContextRequest, opts ...grpc.CallOption) (*InitContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitContextResponse)
	err := c.cc.Invoke(ctx, GPUHEService_InitContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUHEServiceClient) RegisterEvalKeys(ctx context.Context, in *RegisterEvalKeysRequest, opts ...grpc.CallOption) (*RegisterEvalKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEvalKeysResponse)
	err := c.cc.Invoke(ctx, GPUHEService_RegisterEvalKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUHEServiceClient) BatchDotProduct(ctx context.Context, in *BatchDotProductRequest, opts ...grpc.CallOption) (*BatchDotProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDotProductResponse)
	err := c.cc.Invoke(ctx, GPUHEService_BatchDotProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUHEServiceClient) HealthCheck(ctx context.Context, in *GPUHealthCheckRequest, opts ...grpc.CallOption) (*GPUHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPUHealthCheckResponse)
	err := c.cc.Invoke(ctx, GPUHEService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUHEServiceServer is the server API for GPUHEService service.
// All implementations must embed UnimplementedGPUHEServiceServer
// for forward compatibility.
//
// GPUHEService offloads expensive HE operations to a GPU-accelerated server.
//
// Architecture:
//
//	Client (Go/Lattigo) handles: key generation, encryption, decryption
//	GPU Server handles: homomorphic multiply, rescale, Galois rotations, add
//
// The client sends evaluation keys once (RegisterEvalKeys), then sends
// encrypted queries for batch dot product computation. The server never
// has access to secret keys or decrypted data.
//
// Two modes:
//   - CPU stub: uses Lattigo-serialized bytes (bytes fields)
//   - GPU (HEonGPU): uses raw uint64 coefficients (RawPolynomial fields)
type GPUHEServiceServer interface {
	// InitContext creates an HEonGPU context with the given parameters and returns
	// the server's NTT primitive roots (ψ per prime). The client needs these roots
	// to convert evaluation key coefficients from Lattigo's NTT domain to HEonGPU's.
	// Must be called before RegisterEvalKeys.
	InitContext(context.Context, *InitContextRequest) (*InitContextResponse, error)
	// RegisterEvalKeys sends evaluation keys (converted to server's NTT domain).
	RegisterEvalKeys(context.Context, *RegisterEvalKeysRequest) (*RegisterEvalKeysResponse, error)
	// BatchDotProduct computes packed dot products via HE.
	BatchDotProduct(context.Context, *BatchDotProductRequest) (*BatchDotProductResponse, error)
	// HealthCheck reports server status and backend type.
	HealthCheck(context.Context, *GPUHealthCheckRequest) (*GPUHealthCheckResponse, error)
	mustEmbedUnimplementedGPUHEServiceServer()
}

// UnimplementedGPUHEServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUHEServiceServer struct{}

func (UnimplementedGPUHEServiceServer) InitContext(context.Context, *InitContextRequest) (*InitContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitContext not implemented")
}
func (UnimplementedGPUHEServiceServer) RegisterEvalKeys(context.Context, *RegisterEvalKeysRequest) (*RegisterEvalKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEvalKeys not implemented")
}
func (UnimplementedGPUHEServiceServer) BatchDotProduct(context.Context, *BatchDotProductRequest) (*BatchDotProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDotProduct not implemented")
}
func (UnimplementedGPUHEServiceServer) HealthCheck(context.Context, *GPUHealthCheckRequest) (*GPUHealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGPUHEServiceServer) mustEmbedUnimplementedGPUHEServiceServer() {}
func (UnimplementedGPUHEServiceServer) testEmbeddedByValue()                      {}

// UnsafeGPUHEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUHEServiceServer will
// result in compilation errors.
type UnsafeGPUHEServiceServer interface {
	mustEmbedUnimplementedGPUHEServiceServer()
}

func RegisterGPUHEServiceServer(s grpc.ServiceRegistrar, srv GPUHEServiceServer) {
	// If the following call panics, it indicates UnimplementedGPUHEServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUHEService_ServiceDesc, srv)
}

func _GPUHEService_InitContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUHEServiceServer).InitContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUHEService_InitContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUHEServiceServer).InitContext(ctx, req.(*InitContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUHEService_RegisterEvalKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEvalKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUHEServiceServer).RegisterEvalKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUHEService_RegisterEvalKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUHEServiceServer).RegisterEvalKeys(ctx, req.(*RegisterEvalKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUHEService_BatchDotProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDotProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUHEServiceServer).BatchDotProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUHEService_BatchDotProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUHEServiceServer).BatchDotProduct(ctx, req.(*BatchDotProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUHEService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPUHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUHEServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUHEService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUHEServiceServer).HealthCheck(ctx, req.(*GPUHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUHEService_ServiceDesc is the grpc.ServiceDesc for GPUHEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUHEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opaque.gpu.v1.GPUHEService",
	HandlerType: (*GPUHEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitContext",
			Handler:    _GPUHEService_InitContext_Handler,
		},
		{
			MethodName: "RegisterEvalKeys",
			Handler:    _GPUHEService_RegisterEvalKeys_Handler,
		},
		{
			MethodName: "BatchDotProduct",
			Handler:    _GPUHEService_BatchDotProduct_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GPUHEService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpuhe.proto",
}
