// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/gpuhe.proto

package gpuhe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPUHealthCheckResponse_Status int32

const (
	GPUHealthCheckResponse_UNKNOWN     GPUHealthCheckResponse_Status = 0
	GPUHealthCheckResponse_SERVING     GPUHealthCheckResponse_Status = 1
	GPUHealthCheckResponse_NOT_SERVING GPUHealthCheckResponse_Status = 2
)

// Enum value maps for GPUHealthCheckResponse_Status.
var (
	GPUHealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	GPUHealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x GPUHealthCheckResponse_Status) Enum() *GPUHealthCheckResponse_Status {
	p := new(GPUHealthCheckResponse_Status)
	*p = x
	return p
}

func (x GPUHealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUHealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_gpuhe_proto_enumTypes[0].Descriptor()
}

func (GPUHealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_api_proto_gpuhe_proto_enumTypes[0]
}

func (x GPUHealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUHealthCheckResponse_Status.Descriptor instead.
func (GPUHealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{11, 0}
}

type GPUHealthCheckResponse_Backend int32

const (
	GPUHealthCheckResponse_CPU_STUB GPUHealthCheckResponse_Backend = 0
	GPUHealthCheckResponse_CUDA     GPUHealthCheckResponse_Backend = 1
	GPUHealthCheckResponse_METAL    GPUHealthCheckResponse_Backend = 2
)

// Enum value maps for GPUHealthCheckResponse_Backend.
var (
	GPUHealthCheckResponse_Backend_name = map[int32]string{
		0: "CPU_STUB",
		1: "CUDA",
		2: "METAL",
	}
	GPUHealthCheckResponse_Backend_value = map[string]int32{
		"CPU_STUB": 0,
		"CUDA":     1,
		"METAL":    2,
	}
)

func (x GPUHealthCheckResponse_Backend) Enum() *GPUHealthCheckResponse_Backend {
	p := new(GPUHealthCheckResponse_Backend)
	*p = x
	return p
}

func (x GPUHealthCheckResponse_Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUHealthCheckResponse_Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_gpuhe_proto_enumTypes[1].Descriptor()
}

func (GPUHealthCheckResponse_Backend) Type() protoreflect.EnumType {
	return &file_api_proto_gpuhe_proto_enumTypes[1]
}

func (x GPUHealthCheckResponse_Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUHealthCheckResponse_Backend.Descriptor instead.
func (GPUHealthCheckResponse_Backend) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{11, 1}
}

// RawPolynomial represents a single polynomial in RNS+NTT form.
// Layout: coefficients[level * ring_size + i] for level in [0, num_levels), i in [0, ring_size).
// This is the format used for cross-library coefficient transfer (Lattigo ↔ HEonGPU).
type RawPolynomial struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat array of uint64 coefficients: num_levels × ring_size values.
	// Ordered as: [level0_coeff0, level0_coeff1, ..., level0_coeffN-1, level1_coeff0, ...]
	Coefficients []uint64 `protobuf:"varint,1,rep,packed,name=coefficients,proto3" json:"coefficients,omitempty"`
	// Number of active modulus levels in this polynomial.
	NumLevels int32 `protobuf:"varint,2,opt,name=num_levels,json=numLevels,proto3" json:"num_levels,omitempty"`
	// Ring size (N = 2^LogN, e.g., 16384).
	RingSize      int32 `protobuf:"varint,3,opt,name=ring_size,json=ringSize,proto3" json:"ring_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPolynomial) Reset() {
	*x = RawPolynomial{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPolynomial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPolynomial) ProtoMessage() {}

func (x *RawPolynomial) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPolynomial.ProtoReflect.Descriptor instead.
func (*RawPolynomial) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{0}
}

func (x *RawPolynomial) GetCoefficients() []uint64 {
	if x != nil {
		return x.Coefficients
	}
	return nil
}

func (x *RawPolynomial) GetNumLevels() int32 {
	if x != nil {
		return x.NumLevels
	}
	return 0
}

func (x *RawPolynomial) GetRingSize() int32 {
	if x != nil {
		return x.RingSize
	}
	return 0
}

// RawCiphertext represents a CKKS ciphertext as raw polynomial coefficients.
// A standard ciphertext has 2 polynomials (c0, c1).
type RawCiphertext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Polynomials in the ciphertext (typically 2: c0 and c1).
	Polynomials []*RawPolynomial `protobuf:"bytes,1,rep,name=polynomials,proto3" json:"polynomials,omitempty"`
	// CKKS scale factor (e.g., 2^45).
	Scale float64 `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`
	// Whether coefficients are in NTT domain (should always be true for CKKS).
	IsNtt bool `protobuf:"varint,3,opt,name=is_ntt,json=isNtt,proto3" json:"is_ntt,omitempty"`
	// Depth (number of rescale operations performed).
	Depth         int32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawCiphertext) Reset() {
	*x = RawCiphertext{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawCiphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCiphertext) ProtoMessage() {}

func (x *RawCiphertext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCiphertext.ProtoReflect.Descriptor instead.
func (*RawCiphertext) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{1}
}

func (x *RawCiphertext) GetPolynomials() []*RawPolynomial {
	if x != nil {
		return x.Polynomials
	}
	return nil
}

func (x *RawCiphertext) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *RawCiphertext) GetIsNtt() bool {
	if x != nil {
		return x.IsNtt
	}
	return false
}

func (x *RawCiphertext) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// RawPlaintext represents a CKKS plaintext as raw polynomial coefficients.
type RawPlaintext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polynomial    *RawPolynomial         `protobuf:"bytes,1,opt,name=polynomial,proto3" json:"polynomial,omitempty"`
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`
	IsNtt         bool                   `protobuf:"varint,3,opt,name=is_ntt,json=isNtt,proto3" json:"is_ntt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPlaintext) Reset() {
	*x = RawPlaintext{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPlaintext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPlaintext) ProtoMessage() {}

func (x *RawPlaintext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPlaintext.ProtoReflect.Descriptor instead.
func (*RawPlaintext) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{2}
}

func (x *RawPlaintext) GetPolynomial() *RawPolynomial {
	if x != nil {
		return x.Polynomial
	}
	return nil
}

func (x *RawPlaintext) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *RawPlaintext) GetIsNtt() bool {
	if x != nil {
		return x.IsNtt
	}
	return false
}

// CKKSParams contains the CKKS parameter specification needed by the GPU server
// to create a matching HE context.
type CKKSParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log2 of ring degree (e.g., 14 for N=16384).
	LogN int32 `protobuf:"varint,1,opt,name=log_n,json=logN,proto3" json:"log_n,omitempty"`
	// Exact modulus primes for the ciphertext modulus chain Q.
	QModuli []uint64 `protobuf:"varint,2,rep,packed,name=q_moduli,json=qModuli,proto3" json:"q_moduli,omitempty"`
	// Exact modulus primes for the key-switching auxiliary chain P.
	PModuli []uint64 `protobuf:"varint,3,rep,packed,name=p_moduli,json=pModuli,proto3" json:"p_moduli,omitempty"`
	// Default scale (log2, e.g., 45 for scale=2^45).
	LogDefaultScale int32 `protobuf:"varint,4,opt,name=log_default_scale,json=logDefaultScale,proto3" json:"log_default_scale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CKKSParams) Reset() {
	*x = CKKSParams{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CKKSParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CKKSParams) ProtoMessage() {}

func (x *CKKSParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CKKSParams.ProtoReflect.Descriptor instead.
func (*CKKSParams) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{3}
}

func (x *CKKSParams) GetLogN() int32 {
	if x != nil {
		return x.LogN
	}
	return 0
}

func (x *CKKSParams) GetQModuli() []uint64 {
	if x != nil {
		return x.QModuli
	}
	return nil
}

func (x *CKKSParams) GetPModuli() []uint64 {
	if x != nil {
		return x.PModuli
	}
	return nil
}

func (x *CKKSParams) GetLogDefaultScale() int32 {
	if x != nil {
		return x.LogDefaultScale
	}
	return 0
}

// InitContextRequest asks the GPU server to create an HEonGPU context
// with the given CKKS parameters and return its NTT roots.
type InitContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Params        *CKKSParams            `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitContextRequest) Reset() {
	*x = InitContextRequest{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitContextRequest) ProtoMessage() {}

func (x *InitContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitContextRequest.ProtoReflect.Descriptor instead.
func (*InitContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{4}
}

func (x *InitContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitContextRequest) GetParams() *CKKSParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// InitContextResponse returns the server's NTT primitive roots (ψ per prime).
// The client uses these to convert evaluation key coefficients from Lattigo's
// NTT domain to HEonGPU's NTT domain before sending them.
type InitContextResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Primitive 2N-th root of unity (ψ) for each prime in Q∪P order.
	// These are the roots HEonGPU selected for its NTT — they may differ
	// from Lattigo's roots and are non-deterministic across server restarts.
	NttRoots      []uint64 `protobuf:"varint,3,rep,packed,name=ntt_roots,json=nttRoots,proto3" json:"ntt_roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitContextResponse) Reset() {
	*x = InitContextResponse{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitContextResponse) ProtoMessage() {}

func (x *InitContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitContextResponse.ProtoReflect.Descriptor instead.
func (*InitContextResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{5}
}

func (x *InitContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitContextResponse) GetNttRoots() []uint64 {
	if x != nil {
		return x.NttRoots
	}
	return nil
}

// RegisterEvalKeysRequest sends CKKS parameters and evaluation keys.
type RegisterEvalKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID for this client.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// CKKS parameters with exact modulus primes.
	Params *CKKSParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// Galois keys as raw polynomial data.
	// Each key corresponds to one galois_element.
	GaloisKeysSerialized [][]byte `protobuf:"bytes,3,rep,name=galois_keys_serialized,json=galoisKeysSerialized,proto3" json:"galois_keys_serialized,omitempty"`
	GaloisElements       []uint64 `protobuf:"varint,4,rep,packed,name=galois_elements,json=galoisElements,proto3" json:"galois_elements,omitempty"`
	// Relinearization key (serialized).
	RelinKeySerialized []byte `protobuf:"bytes,5,opt,name=relin_key_serialized,json=relinKeySerialized,proto3" json:"relin_key_serialized,omitempty"`
	// Legacy: Lattigo-serialized params (for CPU stub compatibility).
	CkksParamsBinary []byte `protobuf:"bytes,6,opt,name=ckks_params_binary,json=ckksParamsBinary,proto3" json:"ckks_params_binary,omitempty"`
	// HEonGPU-format Galois keys (with NTT domain conversion applied).
	// This is a single binary blob that HEonGPU's Galoiskey::load() can read directly.
	GaloisKeysHeongpu []byte `protobuf:"bytes,7,opt,name=galois_keys_heongpu,json=galoisKeysHeongpu,proto3" json:"galois_keys_heongpu,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterEvalKeysRequest) Reset() {
	*x = RegisterEvalKeysRequest{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvalKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvalKeysRequest) ProtoMessage() {}

func (x *RegisterEvalKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvalKeysRequest.ProtoReflect.Descriptor instead.
func (*RegisterEvalKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterEvalKeysRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterEvalKeysRequest) GetParams() *CKKSParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetGaloisKeysSerialized() [][]byte {
	if x != nil {
		return x.GaloisKeysSerialized
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetGaloisElements() []uint64 {
	if x != nil {
		return x.GaloisElements
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetRelinKeySerialized() []byte {
	if x != nil {
		return x.RelinKeySerialized
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetCkksParamsBinary() []byte {
	if x != nil {
		return x.CkksParamsBinary
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetGaloisKeysHeongpu() []byte {
	if x != nil {
		return x.GaloisKeysHeongpu
	}
	return nil
}

type RegisterEvalKeysResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	GpuMemoryBytes uint64                 `protobuf:"varint,3,opt,name=gpu_memory_bytes,json=gpuMemoryBytes,proto3" json:"gpu_memory_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterEvalKeysResponse) Reset() {
	*x = RegisterEvalKeysResponse{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvalKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvalKeysResponse) ProtoMessage() {}

func (x *RegisterEvalKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvalKeysResponse.ProtoReflect.Descriptor instead.
func (*RegisterEvalKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterEvalKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterEvalKeysResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterEvalKeysResponse) GetGpuMemoryBytes() uint64 {
	if x != nil {
		return x.GpuMemoryBytes
	}
	return 0
}

// BatchDotProductRequest sends encrypted query and plaintext centroids.
type BatchDotProductRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Raw coefficient format (for HEonGPU GPU backend).
	RawQuery     *RawCiphertext `protobuf:"bytes,2,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	RawCentroids *RawPlaintext  `protobuf:"bytes,3,opt,name=raw_centroids,json=rawCentroids,proto3" json:"raw_centroids,omitempty"`
	// Legacy: Lattigo-serialized format (for CPU stub backend).
	EncryptedQuery  []byte `protobuf:"bytes,4,opt,name=encrypted_query,json=encryptedQuery,proto3" json:"encrypted_query,omitempty"`
	PackedCentroids []byte `protobuf:"bytes,5,opt,name=packed_centroids,json=packedCentroids,proto3" json:"packed_centroids,omitempty"`
	// Computation parameters.
	NumCentroids int32 `protobuf:"varint,6,opt,name=num_centroids,json=numCentroids,proto3" json:"num_centroids,omitempty"`
	Dimension    int32 `protobuf:"varint,7,opt,name=dimension,proto3" json:"dimension,omitempty"`
	// Raw float64 plaintext values — server encodes natively with HEonGPU encoder.
	// This avoids NTT domain conversion for the plaintext entirely.
	PlaintextValues []float64 `protobuf:"fixed64,8,rep,packed,name=plaintext_values,json=plaintextValues,proto3" json:"plaintext_values,omitempty"`
	// Scale for encoding (e.g., 2^45). Required when plaintext_values is used.
	PlaintextScale float64 `protobuf:"fixed64,9,opt,name=plaintext_scale,json=plaintextScale,proto3" json:"plaintext_scale,omitempty"`
	// If true, raw_query coefficients are in COEFFICIENT domain (not NTT).
	// The server will apply its own NTT before computing.
	// This avoids cross-library NTT conversion issues entirely.
	QueryIsCoeffDomain bool `protobuf:"varint,10,opt,name=query_is_coeff_domain,json=queryIsCoeffDomain,proto3" json:"query_is_coeff_domain,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchDotProductRequest) Reset() {
	*x = BatchDotProductRequest{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDotProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDotProductRequest) ProtoMessage() {}

func (x *BatchDotProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDotProductRequest.ProtoReflect.Descriptor instead.
func (*BatchDotProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{8}
}

func (x *BatchDotProductRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchDotProductRequest) GetRawQuery() *RawCiphertext {
	if x != nil {
		return x.RawQuery
	}
	return nil
}

func (x *BatchDotProductRequest) GetRawCentroids() *RawPlaintext {
	if x != nil {
		return x.RawCentroids
	}
	return nil
}

func (x *BatchDotProductRequest) GetEncryptedQuery() []byte {
	if x != nil {
		return x.EncryptedQuery
	}
	return nil
}

func (x *BatchDotProductRequest) GetPackedCentroids() []byte {
	if x != nil {
		return x.PackedCentroids
	}
	return nil
}

func (x *BatchDotProductRequest) GetNumCentroids() int32 {
	if x != nil {
		return x.NumCentroids
	}
	return 0
}

func (x *BatchDotProductRequest) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *BatchDotProductRequest) GetPlaintextValues() []float64 {
	if x != nil {
		return x.PlaintextValues
	}
	return nil
}

func (x *BatchDotProductRequest) GetPlaintextScale() float64 {
	if x != nil {
		return x.PlaintextScale
	}
	return 0
}

func (x *BatchDotProductRequest) GetQueryIsCoeffDomain() bool {
	if x != nil {
		return x.QueryIsCoeffDomain
	}
	return false
}

type BatchDotProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw coefficient result (for HEonGPU GPU backend).
	RawResult *RawCiphertext `protobuf:"bytes,1,opt,name=raw_result,json=rawResult,proto3" json:"raw_result,omitempty"`
	// Legacy: Lattigo-serialized result (for CPU stub backend).
	EncryptedResult []byte `protobuf:"bytes,2,opt,name=encrypted_result,json=encryptedResult,proto3" json:"encrypted_result,omitempty"`
	Error           string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Timing (microseconds).
	ComputeTimeUs int64 `protobuf:"varint,4,opt,name=compute_time_us,json=computeTimeUs,proto3" json:"compute_time_us,omitempty"`
	MultiplyUs    int64 `protobuf:"varint,5,opt,name=multiply_us,json=multiplyUs,proto3" json:"multiply_us,omitempty"`
	RescaleUs     int64 `protobuf:"varint,6,opt,name=rescale_us,json=rescaleUs,proto3" json:"rescale_us,omitempty"`
	RotateUs      int64 `protobuf:"varint,7,opt,name=rotate_us,json=rotateUs,proto3" json:"rotate_us,omitempty"`
	AddUs         int64 `protobuf:"varint,8,opt,name=add_us,json=addUs,proto3" json:"add_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDotProductResponse) Reset() {
	*x = BatchDotProductResponse{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDotProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDotProductResponse) ProtoMessage() {}

func (x *BatchDotProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDotProductResponse.ProtoReflect.Descriptor instead.
func (*BatchDotProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDotProductResponse) GetRawResult() *RawCiphertext {
	if x != nil {
		return x.RawResult
	}
	return nil
}

func (x *BatchDotProductResponse) GetEncryptedResult() []byte {
	if x != nil {
		return x.EncryptedResult
	}
	return nil
}

func (x *BatchDotProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BatchDotProductResponse) GetComputeTimeUs() int64 {
	if x != nil {
		return x.ComputeTimeUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetMultiplyUs() int64 {
	if x != nil {
		return x.MultiplyUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetRescaleUs() int64 {
	if x != nil {
		return x.RescaleUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetRotateUs() int64 {
	if x != nil {
		return x.RotateUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetAddUs() int64 {
	if x != nil {
		return x.AddUs
	}
	return 0
}

// GPUHealthCheckRequest is empty.
type GPUHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUHealthCheckRequest) Reset() {
	*x = GPUHealthCheckRequest{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHealthCheckRequest) ProtoMessage() {}

func (x *GPUHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*GPUHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{10}
}

type GPUHealthCheckResponse struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Status         GPUHealthCheckResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=opaque.gpu.v1.GPUHealthCheckResponse_Status" json:"status,omitempty"`
	Backend        GPUHealthCheckResponse_Backend `protobuf:"varint,2,opt,name=backend,proto3,enum=opaque.gpu.v1.GPUHealthCheckResponse_Backend" json:"backend,omitempty"`
	DeviceName     string                         `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ActiveSessions int32                          `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GPUHealthCheckResponse) Reset() {
	*x = GPUHealthCheckResponse{}
	mi := &file_api_proto_gpuhe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHealthCheckResponse) ProtoMessage() {}

func (x *GPUHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gpuhe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*GPUHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gpuhe_proto_rawDescGZIP(), []int{11}
}

func (x *GPUHealthCheckResponse) GetStatus() GPUHealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return GPUHealthCheckResponse_UNKNOWN
}

func (x *GPUHealthCheckResponse) GetBackend() GPUHealthCheckResponse_Backend {
	if x != nil {
		return x.Backend
	}
	return GPUHealthCheckResponse_CPU_STUB
}

func (x *GPUHealthCheckResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GPUHealthCheckResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

var File_api_proto_gpuhe_proto protoreflect.FileDescriptor

const file_api_proto_gpuhe_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/gpuhe.proto\x12\ropaque.gpu.v1\"s\n" +
	"\rRawPolynomial\x12&\n" +
	"\fcoefficients\x18\x01 \x03(\x04B\x02\x10\x01R\fcoefficients\x12\x1d\n" +
	"\n" +
	"num_levels\x18\x02 \x01(\x05R\tnumLevels\x12\x1b\n" +
	"\tring_size\x18\x03 \x01(\x05R\bringSize\"\x92\x01\n" +
	"\rRawCiphertext\x12>\n" +
	"\vpolynomials\x18\x01 \x03(\v2\x1c.opaque.gpu.v1.RawPolynomialR\vpolynomials\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x15\n" +
	"\x06is_ntt\x18\x03 \x01(\bR\x05isNtt\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\"y\n" +
	"\fRawPlaintext\x12<\n" +
	"\n" +
	"polynomial\x18\x01 \x01(\v2\x1c.opaque.gpu.v1.RawPolynomialR\n" +
	"polynomial\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x15\n" +
	"\x06is_ntt\x18\x03 \x01(\bR\x05isNtt\"\x8b\x01\n" +
	"\n" +
	"CKKSParams\x12\x13\n" +
	"\x05log_n\x18\x01 \x01(\x05R\x04logN\x12\x1d\n" +
	"\bq_moduli\x18\x02 \x03(\x04B\x02\x10\x01R\aqModuli\x12\x1d\n" +
	"\bp_moduli\x18\x03 \x03(\x04B\x02\x10\x01R\apModuli\x12*\n" +
	"\x11log_default_scale\x18\x04 \x01(\x05R\x0flogDefaultScale\"f\n" +
	"\x12InitContextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x06params\x18\x02 \x01(\v2\x19.opaque.gpu.v1.CKKSParamsR\x06params\"f\n" +
	"\x13InitContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\tntt_roots\x18\x03 \x03(\x04B\x02\x10\x01R\bnttRoots\"\xde\x02\n" +
	"\x17RegisterEvalKeysRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x06params\x18\x02 \x01(\v2\x19.opaque.gpu.v1.CKKSParamsR\x06params\x124\n" +
	"\x16galois_keys_serialized\x18\x03 \x03(\fR\x14galoisKeysSerialized\x12+\n" +
	"\x0fgalois_elements\x18\x04 \x03(\x04B\x02\x10\x01R\x0egaloisElements\x120\n" +
	"\x14relin_key_serialized\x18\x05 \x01(\fR\x12relinKeySerialized\x12,\n" +
	"\x12ckks_params_binary\x18\x06 \x01(\fR\x10ckksParamsBinary\x12.\n" +
	"\x13galois_keys_heongpu\x18\a \x01(\fR\x11galoisKeysHeongpu\"t\n" +
	"\x18RegisterEvalKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x10gpu_memory_bytes\x18\x03 \x01(\x04R\x0egpuMemoryBytes\"\xd6\x03\n" +
	"\x16BatchDotProductRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\traw_query\x18\x02 \x01(\v2\x1c.opaque.gpu.v1.RawCiphertextR\brawQuery\x12@\n" +
	"\rraw_centroids\x18\x03 \x01(\v2\x1b.opaque.gpu.v1.RawPlaintextR\frawCentroids\x12'\n" +
	"\x0fencrypted_query\x18\x04 \x01(\fR\x0eencryptedQuery\x12)\n" +
	"\x10packed_centroids\x18\x05 \x01(\fR\x0fpackedCentroids\x12#\n" +
	"\rnum_centroids\x18\x06 \x01(\x05R\fnumCentroids\x12\x1c\n" +
	"\tdimension\x18\a \x01(\x05R\tdimension\x12-\n" +
	"\x10plaintext_values\x18\b \x03(\x01B\x02\x10\x01R\x0fplaintextValues\x12'\n" +
	"\x0fplaintext_scale\x18\t \x01(\x01R\x0eplaintextScale\x121\n" +
	"\x15query_is_coeff_domain\x18\n" +
	" \x01(\bR\x12queryIsCoeffDomain\"\xb3\x02\n" +
	"\x17BatchDotProductResponse\x12;\n" +
	"\n" +
	"raw_result\x18\x01 \x01(\v2\x1c.opaque.gpu.v1.RawCiphertextR\trawResult\x12)\n" +
	"\x10encrypted_result\x18\x02 \x01(\fR\x0fencryptedResult\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12&\n" +
	"\x0fcompute_time_us\x18\x04 \x01(\x03R\rcomputeTimeUs\x12\x1f\n" +
	"\vmultiply_us\x18\x05 \x01(\x03R\n" +
	"multiplyUs\x12\x1d\n" +
	"\n" +
	"rescale_us\x18\x06 \x01(\x03R\trescaleUs\x12\x1b\n" +
	"\trotate_us\x18\a \x01(\x03R\brotateUs\x12\x15\n" +
	"\x06add_us\x18\b \x01(\x03R\x05addUs\"\x17\n" +
	"\x15GPUHealthCheckRequest\"\xd4\x02\n" +
	"\x16GPUHealthCheckResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.opaque.gpu.v1.GPUHealthCheckResponse.StatusR\x06status\x12G\n" +
	"\abackend\x18\x02 \x01(\x0e2-.opaque.gpu.v1.GPUHealthCheckResponse.BackendR\abackend\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\",\n" +
	"\aBackend\x12\f\n" +
	"\bCPU_STUB\x10\x00\x12\b\n" +
	"\x04CUDA\x10\x01\x12\t\n" +
	"\x05METAL\x10\x022\x87\x03\n" +
	"\fGPUHEService\x12T\n" +
	"\vInitContext\x12!.opaque.gpu.v1.InitContextRequest\x1a\".opaque.gpu.v1.InitContextResponse\x12c\n" +
	"\x10RegisterEvalKeys\x12&.opaque.gpu.v1.RegisterEvalKeysRequest\x1a'.opaque.gpu.v1.RegisterEvalKeysResponse\x12`\n" +
	"\x0fBatchDotProduct\x12%.opaque.gpu.v1.BatchDotProductRequest\x1a&.opaque.gpu.v1.BatchDotProductResponse\x12Z\n" +
	"\vHealthCheck\x12$.opaque.gpu.v1.GPUHealthCheckRequest\x1a%.opaque.gpu.v1.GPUHealthCheckResponseB4Z2github.com/Prasad-178/opaque/api/proto/gpuhe;gpuheb\x06proto3"

var (
	file_api_proto_gpuhe_proto_rawDescOnce sync.Once
	file_api_proto_gpuhe_proto_rawDescData []byte
)

func file_api_proto_gpuhe_proto_rawDescGZIP() []byte {
	file_api_proto_gpuhe_proto_rawDescOnce.Do(func() {
		file_api_proto_gpuhe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gpuhe_proto_rawDesc), len(file_api_proto_gpuhe_proto_rawDesc)))
	})
	return file_api_proto_gpuhe_proto_rawDescData
}

var file_api_proto_gpuhe_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_gpuhe_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_gpuhe_proto_goTypes = []any{
	(GPUHealthCheckResponse_Status)(0),  // 0: opaque.gpu.v1.GPUHealthCheckResponse.Status
	(GPUHealthCheckResponse_Backend)(0), // 1: opaque.gpu.v1.GPUHealthCheckResponse.Backend
	(*RawPolynomial)(nil),               // 2: opaque.gpu.v1.RawPolynomial
	(*RawCiphertext)(nil),               // 3: opaque.gpu.v1.RawCiphertext
	(*RawPlaintext)(nil),                // 4: opaque.gpu.v1.RawPlaintext
	(*CKKSParams)(nil),                  // 5: opaque.gpu.v1.CKKSParams
	(*InitContextRequest)(nil),          // 6: opaque.gpu.v1.InitContextRequest
	(*InitContextResponse)(nil),         // 7: opaque.gpu.v1.InitContextResponse
	(*RegisterEvalKeysRequest)(nil),     // 8: opaque.gpu.v1.RegisterEvalKeysRequest
	(*RegisterEvalKeysResponse)(nil),    // 9: opaque.gpu.v1.RegisterEvalKeysResponse
	(*BatchDotProductRequest)(nil),      // 10: opaque.gpu.v1.BatchDotProductRequest
	(*BatchDotProductResponse)(nil),     // 11: opaque.gpu.v1.BatchDotProductResponse
	(*GPUHealthCheckRequest)(nil),       // 12: opaque.gpu.v1.GPUHealthCheckRequest
	(*GPUHealthCheckResponse)(nil),      // 13: opaque.gpu.v1.GPUHealthCheckResponse
}
var file_api_proto_gpuhe_proto_depIdxs = []int32{
	2,  // 0: opaque.gpu.v1.RawCiphertext.polynomials:type_name -> opaque.gpu.v1.RawPolynomial
	2,  // 1: opaque.gpu.v1.RawPlaintext.polynomial:type_name -> opaque.gpu.v1.RawPolynomial
	5,  // 2: opaque.gpu.v1.InitContextRequest.params:type_name -> opaque.gpu.v1.CKKSParams
	5,  // 3: opaque.gpu.v1.RegisterEvalKeysRequest.params:type_name -> opaque.gpu.v1.CKKSParams
	3,  // 4: opaque.gpu.v1.BatchDotProductRequest.raw_query:type_name -> opaque.gpu.v1.RawCiphertext
	4,  // 5: opaque.gpu.v1.BatchDotProductRequest.raw_centroids:type_name -> opaque.gpu.v1.RawPlaintext
	3,  // 6: opaque.gpu.v1.BatchDotProductResponse.raw_result:type_name -> opaque.gpu.v1.RawCiphertext
	0,  // 7: opaque.gpu.v1.GPUHealthCheckResponse.status:type_name -> opaque.gpu.v1.GPUHealthCheckResponse.Status
	1,  // 8: opaque.gpu.v1.GPUHealthCheckResponse.backend:type_name -> opaque.gpu.v1.GPUHealthCheckResponse.Backend
	6,  // 9: opaque.gpu.v1.GPUHEService.InitContext:input_type -> opaque.gpu.v1.InitContextRequest
	8,  // 10: opaque.gpu.v1.GPUHEService.RegisterEvalKeys:input_type -> opaque.gpu.v1.RegisterEvalKeysRequest
	10, // 11: opaque.gpu.v1.GPUHEService.BatchDotProduct:input_type -> opaque.gpu.v1.BatchDotProductRequest
	12, // 12: opaque.gpu.v1.GPUHEService.HealthCheck:input_type -> opaque.gpu.v1.GPUHealthCheckRequest
	7,  // 13: opaque.gpu.v1.GPUHEService.InitContext:output_type -> opaque.gpu.v1.InitContextResponse
	9,  // 14: opaque.gpu.v1.GPUHEService.RegisterEvalKeys:output_type -> opaque.gpu.v1.RegisterEvalKeysResponse
	11, // 15: opaque.gpu.v1.GPUHEService.BatchDotProduct:output_type -> opaque.gpu.v1.BatchDotProductResponse
	13, // 16: opaque.gpu.v1.GPUHEService.HealthCheck:output_type -> opaque.gpu.v1.GPUHealthCheckResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_gpuhe_proto_init() }
func file_api_proto_gpuhe_proto_init() {
	if File_api_proto_gpuhe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gpuhe_proto_rawDesc), len(file_api_proto_gpuhe_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gpuhe_proto_goTypes,
		DependencyIndexes: file_api_proto_gpuhe_proto_depIdxs,
		EnumInfos:         file_api_proto_gpuhe_proto_enumTypes,
		MessageInfos:      file_api_proto_gpuhe_proto_msgTypes,
	}.Build()
	File_api_proto_gpuhe_proto = out.File
	file_api_proto_gpuhe_proto_goTypes = nil
	file_api_proto_gpuhe_proto_depIdxs = nil
}
