// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gpuhe.proto

package gpuhe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPUHealthCheckResponse_Status int32

const (
	GPUHealthCheckResponse_UNKNOWN     GPUHealthCheckResponse_Status = 0
	GPUHealthCheckResponse_SERVING     GPUHealthCheckResponse_Status = 1
	GPUHealthCheckResponse_NOT_SERVING GPUHealthCheckResponse_Status = 2
)

// Enum value maps for GPUHealthCheckResponse_Status.
var (
	GPUHealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	GPUHealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x GPUHealthCheckResponse_Status) Enum() *GPUHealthCheckResponse_Status {
	p := new(GPUHealthCheckResponse_Status)
	*p = x
	return p
}

func (x GPUHealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUHealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_gpuhe_proto_enumTypes[0].Descriptor()
}

func (GPUHealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_gpuhe_proto_enumTypes[0]
}

func (x GPUHealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUHealthCheckResponse_Status.Descriptor instead.
func (GPUHealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{5, 0}
}

type GPUHealthCheckResponse_Backend int32

const (
	GPUHealthCheckResponse_CPU_STUB GPUHealthCheckResponse_Backend = 0 // Lattigo CPU (for testing without GPU)
	GPUHealthCheckResponse_CUDA     GPUHealthCheckResponse_Backend = 1 // HEonGPU / custom CUDA
	GPUHealthCheckResponse_METAL    GPUHealthCheckResponse_Backend = 2 // Apple Metal (future)
)

// Enum value maps for GPUHealthCheckResponse_Backend.
var (
	GPUHealthCheckResponse_Backend_name = map[int32]string{
		0: "CPU_STUB",
		1: "CUDA",
		2: "METAL",
	}
	GPUHealthCheckResponse_Backend_value = map[string]int32{
		"CPU_STUB": 0,
		"CUDA":     1,
		"METAL":    2,
	}
)

func (x GPUHealthCheckResponse_Backend) Enum() *GPUHealthCheckResponse_Backend {
	p := new(GPUHealthCheckResponse_Backend)
	*p = x
	return p
}

func (x GPUHealthCheckResponse_Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUHealthCheckResponse_Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_gpuhe_proto_enumTypes[1].Descriptor()
}

func (GPUHealthCheckResponse_Backend) Type() protoreflect.EnumType {
	return &file_gpuhe_proto_enumTypes[1]
}

func (x GPUHealthCheckResponse_Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUHealthCheckResponse_Backend.Descriptor instead.
func (GPUHealthCheckResponse_Backend) EnumDescriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{5, 1}
}

// RegisterEvalKeysRequest contains serialized CKKS evaluation keys.
type RegisterEvalKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized CKKS parameters (hefloat.Parameters via MarshalBinary).
	CkksParams []byte `protobuf:"bytes,1,opt,name=ckks_params,json=ckksParams,proto3" json:"ckks_params,omitempty"`
	// Serialized relinearization key (rlwe.RelinearizationKey via WriteTo).
	RelinKey []byte `protobuf:"bytes,2,opt,name=relin_key,json=relinKey,proto3" json:"relin_key,omitempty"`
	// Serialized Galois keys. Each entry is one GaloisKey via WriteTo.
	// The server needs one key per rotation step used in batch dot product.
	GaloisKeys [][]byte `protobuf:"bytes,3,rep,name=galois_keys,json=galoisKeys,proto3" json:"galois_keys,omitempty"`
	// Galois elements corresponding to each Galois key (for the evaluator).
	GaloisElements []uint64 `protobuf:"varint,4,rep,packed,name=galois_elements,json=galoisElements,proto3" json:"galois_elements,omitempty"`
	// Session ID for this client (allows multiple clients).
	SessionId     string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEvalKeysRequest) Reset() {
	*x = RegisterEvalKeysRequest{}
	mi := &file_gpuhe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvalKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvalKeysRequest) ProtoMessage() {}

func (x *RegisterEvalKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvalKeysRequest.ProtoReflect.Descriptor instead.
func (*RegisterEvalKeysRequest) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEvalKeysRequest) GetCkksParams() []byte {
	if x != nil {
		return x.CkksParams
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetRelinKey() []byte {
	if x != nil {
		return x.RelinKey
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetGaloisKeys() [][]byte {
	if x != nil {
		return x.GaloisKeys
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetGaloisElements() []uint64 {
	if x != nil {
		return x.GaloisElements
	}
	return nil
}

func (x *RegisterEvalKeysRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RegisterEvalKeysResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Server-reported memory usage after loading keys.
	GpuMemoryBytes uint64 `protobuf:"varint,3,opt,name=gpu_memory_bytes,json=gpuMemoryBytes,proto3" json:"gpu_memory_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterEvalKeysResponse) Reset() {
	*x = RegisterEvalKeysResponse{}
	mi := &file_gpuhe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvalKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvalKeysResponse) ProtoMessage() {}

func (x *RegisterEvalKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvalKeysResponse.ProtoReflect.Descriptor instead.
func (*RegisterEvalKeysResponse) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterEvalKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterEvalKeysResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterEvalKeysResponse) GetGpuMemoryBytes() uint64 {
	if x != nil {
		return x.GpuMemoryBytes
	}
	return 0
}

// BatchDotProductRequest contains serialized ciphertext and plaintext for batch computation.
type BatchDotProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID (must match a previous RegisterEvalKeys call).
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Serialized encrypted packed query (rlwe.Ciphertext via WriteTo).
	EncryptedQuery []byte `protobuf:"bytes,2,opt,name=encrypted_query,json=encryptedQuery,proto3" json:"encrypted_query,omitempty"`
	// Serialized packed centroids plaintext (rlwe.Plaintext via WriteTo).
	PackedCentroids []byte `protobuf:"bytes,3,opt,name=packed_centroids,json=packedCentroids,proto3" json:"packed_centroids,omitempty"`
	// Number of centroids packed in the plaintext.
	NumCentroids int32 `protobuf:"varint,4,opt,name=num_centroids,json=numCentroids,proto3" json:"num_centroids,omitempty"`
	// Vector dimension (for rotation count calculation).
	Dimension     int32 `protobuf:"varint,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDotProductRequest) Reset() {
	*x = BatchDotProductRequest{}
	mi := &file_gpuhe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDotProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDotProductRequest) ProtoMessage() {}

func (x *BatchDotProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDotProductRequest.ProtoReflect.Descriptor instead.
func (*BatchDotProductRequest) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{2}
}

func (x *BatchDotProductRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchDotProductRequest) GetEncryptedQuery() []byte {
	if x != nil {
		return x.EncryptedQuery
	}
	return nil
}

func (x *BatchDotProductRequest) GetPackedCentroids() []byte {
	if x != nil {
		return x.PackedCentroids
	}
	return nil
}

func (x *BatchDotProductRequest) GetNumCentroids() int32 {
	if x != nil {
		return x.NumCentroids
	}
	return 0
}

func (x *BatchDotProductRequest) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

type BatchDotProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized encrypted result (rlwe.Ciphertext via WriteTo).
	// Contains dot products at positions [0, dim, 2*dim, ...].
	EncryptedResult []byte `protobuf:"bytes,1,opt,name=encrypted_result,json=encryptedResult,proto3" json:"encrypted_result,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Server-side computation time in microseconds.
	ComputeTimeUs int64 `protobuf:"varint,3,opt,name=compute_time_us,json=computeTimeUs,proto3" json:"compute_time_us,omitempty"`
	// Sub-phase timing (for profiling).
	MultiplyUs    int64 `protobuf:"varint,4,opt,name=multiply_us,json=multiplyUs,proto3" json:"multiply_us,omitempty"`
	RescaleUs     int64 `protobuf:"varint,5,opt,name=rescale_us,json=rescaleUs,proto3" json:"rescale_us,omitempty"`
	RotateUs      int64 `protobuf:"varint,6,opt,name=rotate_us,json=rotateUs,proto3" json:"rotate_us,omitempty"`
	AddUs         int64 `protobuf:"varint,7,opt,name=add_us,json=addUs,proto3" json:"add_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDotProductResponse) Reset() {
	*x = BatchDotProductResponse{}
	mi := &file_gpuhe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDotProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDotProductResponse) ProtoMessage() {}

func (x *BatchDotProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDotProductResponse.ProtoReflect.Descriptor instead.
func (*BatchDotProductResponse) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{3}
}

func (x *BatchDotProductResponse) GetEncryptedResult() []byte {
	if x != nil {
		return x.EncryptedResult
	}
	return nil
}

func (x *BatchDotProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BatchDotProductResponse) GetComputeTimeUs() int64 {
	if x != nil {
		return x.ComputeTimeUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetMultiplyUs() int64 {
	if x != nil {
		return x.MultiplyUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetRescaleUs() int64 {
	if x != nil {
		return x.RescaleUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetRotateUs() int64 {
	if x != nil {
		return x.RotateUs
	}
	return 0
}

func (x *BatchDotProductResponse) GetAddUs() int64 {
	if x != nil {
		return x.AddUs
	}
	return 0
}

// GPUHealthCheckRequest is empty.
type GPUHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUHealthCheckRequest) Reset() {
	*x = GPUHealthCheckRequest{}
	mi := &file_gpuhe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHealthCheckRequest) ProtoMessage() {}

func (x *GPUHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*GPUHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{4}
}

type GPUHealthCheckResponse struct {
	state   protoimpl.MessageState         `protogen:"open.v1"`
	Status  GPUHealthCheckResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=opaque.gpu.v1.GPUHealthCheckResponse_Status" json:"status,omitempty"`
	Backend GPUHealthCheckResponse_Backend `protobuf:"varint,2,opt,name=backend,proto3,enum=opaque.gpu.v1.GPUHealthCheckResponse_Backend" json:"backend,omitempty"`
	// GPU device name (e.g., "Tesla T4", "Apple M4 GPU").
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Number of active sessions.
	ActiveSessions int32 `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GPUHealthCheckResponse) Reset() {
	*x = GPUHealthCheckResponse{}
	mi := &file_gpuhe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUHealthCheckResponse) ProtoMessage() {}

func (x *GPUHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpuhe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*GPUHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_gpuhe_proto_rawDescGZIP(), []int{5}
}

func (x *GPUHealthCheckResponse) GetStatus() GPUHealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return GPUHealthCheckResponse_UNKNOWN
}

func (x *GPUHealthCheckResponse) GetBackend() GPUHealthCheckResponse_Backend {
	if x != nil {
		return x.Backend
	}
	return GPUHealthCheckResponse_CPU_STUB
}

func (x *GPUHealthCheckResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GPUHealthCheckResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

var File_gpuhe_proto protoreflect.FileDescriptor

const file_gpuhe_proto_rawDesc = "" +
	"\n" +
	"\vgpuhe.proto\x12\ropaque.gpu.v1\"\xc0\x01\n" +
	"\x17RegisterEvalKeysRequest\x12\x1f\n" +
	"\vckks_params\x18\x01 \x01(\fR\n" +
	"ckksParams\x12\x1b\n" +
	"\trelin_key\x18\x02 \x01(\fR\brelinKey\x12\x1f\n" +
	"\vgalois_keys\x18\x03 \x03(\fR\n" +
	"galoisKeys\x12'\n" +
	"\x0fgalois_elements\x18\x04 \x03(\x04R\x0egaloisElements\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"t\n" +
	"\x18RegisterEvalKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x10gpu_memory_bytes\x18\x03 \x01(\x04R\x0egpuMemoryBytes\"\xce\x01\n" +
	"\x16BatchDotProductRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fencrypted_query\x18\x02 \x01(\fR\x0eencryptedQuery\x12)\n" +
	"\x10packed_centroids\x18\x03 \x01(\fR\x0fpackedCentroids\x12#\n" +
	"\rnum_centroids\x18\x04 \x01(\x05R\fnumCentroids\x12\x1c\n" +
	"\tdimension\x18\x05 \x01(\x05R\tdimension\"\xf6\x01\n" +
	"\x17BatchDotProductResponse\x12)\n" +
	"\x10encrypted_result\x18\x01 \x01(\fR\x0fencryptedResult\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x0fcompute_time_us\x18\x03 \x01(\x03R\rcomputeTimeUs\x12\x1f\n" +
	"\vmultiply_us\x18\x04 \x01(\x03R\n" +
	"multiplyUs\x12\x1d\n" +
	"\n" +
	"rescale_us\x18\x05 \x01(\x03R\trescaleUs\x12\x1b\n" +
	"\trotate_us\x18\x06 \x01(\x03R\brotateUs\x12\x15\n" +
	"\x06add_us\x18\a \x01(\x03R\x05addUs\"\x17\n" +
	"\x15GPUHealthCheckRequest\"\xd4\x02\n" +
	"\x16GPUHealthCheckResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.opaque.gpu.v1.GPUHealthCheckResponse.StatusR\x06status\x12G\n" +
	"\abackend\x18\x02 \x01(\x0e2-.opaque.gpu.v1.GPUHealthCheckResponse.BackendR\abackend\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\",\n" +
	"\aBackend\x12\f\n" +
	"\bCPU_STUB\x10\x00\x12\b\n" +
	"\x04CUDA\x10\x01\x12\t\n" +
	"\x05METAL\x10\x022\xb1\x02\n" +
	"\fGPUHEService\x12c\n" +
	"\x10RegisterEvalKeys\x12&.opaque.gpu.v1.RegisterEvalKeysRequest\x1a'.opaque.gpu.v1.RegisterEvalKeysResponse\x12`\n" +
	"\x0fBatchDotProduct\x12%.opaque.gpu.v1.BatchDotProductRequest\x1a&.opaque.gpu.v1.BatchDotProductResponse\x12Z\n" +
	"\vHealthCheck\x12$.opaque.gpu.v1.GPUHealthCheckRequest\x1a%.opaque.gpu.v1.GPUHealthCheckResponseB4Z2github.com/Prasad-178/opaque/api/proto/gpuhe;gpuheb\x06proto3"

var (
	file_gpuhe_proto_rawDescOnce sync.Once
	file_gpuhe_proto_rawDescData []byte
)

func file_gpuhe_proto_rawDescGZIP() []byte {
	file_gpuhe_proto_rawDescOnce.Do(func() {
		file_gpuhe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpuhe_proto_rawDesc), len(file_gpuhe_proto_rawDesc)))
	})
	return file_gpuhe_proto_rawDescData
}

var file_gpuhe_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gpuhe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gpuhe_proto_goTypes = []any{
	(GPUHealthCheckResponse_Status)(0),  // 0: opaque.gpu.v1.GPUHealthCheckResponse.Status
	(GPUHealthCheckResponse_Backend)(0), // 1: opaque.gpu.v1.GPUHealthCheckResponse.Backend
	(*RegisterEvalKeysRequest)(nil),     // 2: opaque.gpu.v1.RegisterEvalKeysRequest
	(*RegisterEvalKeysResponse)(nil),    // 3: opaque.gpu.v1.RegisterEvalKeysResponse
	(*BatchDotProductRequest)(nil),      // 4: opaque.gpu.v1.BatchDotProductRequest
	(*BatchDotProductResponse)(nil),     // 5: opaque.gpu.v1.BatchDotProductResponse
	(*GPUHealthCheckRequest)(nil),       // 6: opaque.gpu.v1.GPUHealthCheckRequest
	(*GPUHealthCheckResponse)(nil),      // 7: opaque.gpu.v1.GPUHealthCheckResponse
}
var file_gpuhe_proto_depIdxs = []int32{
	0, // 0: opaque.gpu.v1.GPUHealthCheckResponse.status:type_name -> opaque.gpu.v1.GPUHealthCheckResponse.Status
	1, // 1: opaque.gpu.v1.GPUHealthCheckResponse.backend:type_name -> opaque.gpu.v1.GPUHealthCheckResponse.Backend
	2, // 2: opaque.gpu.v1.GPUHEService.RegisterEvalKeys:input_type -> opaque.gpu.v1.RegisterEvalKeysRequest
	4, // 3: opaque.gpu.v1.GPUHEService.BatchDotProduct:input_type -> opaque.gpu.v1.BatchDotProductRequest
	6, // 4: opaque.gpu.v1.GPUHEService.HealthCheck:input_type -> opaque.gpu.v1.GPUHealthCheckRequest
	3, // 5: opaque.gpu.v1.GPUHEService.RegisterEvalKeys:output_type -> opaque.gpu.v1.RegisterEvalKeysResponse
	5, // 6: opaque.gpu.v1.GPUHEService.BatchDotProduct:output_type -> opaque.gpu.v1.BatchDotProductResponse
	7, // 7: opaque.gpu.v1.GPUHEService.HealthCheck:output_type -> opaque.gpu.v1.GPUHealthCheckResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gpuhe_proto_init() }
func file_gpuhe_proto_init() {
	if File_gpuhe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpuhe_proto_rawDesc), len(file_gpuhe_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpuhe_proto_goTypes,
		DependencyIndexes: file_gpuhe_proto_depIdxs,
		EnumInfos:         file_gpuhe_proto_enumTypes,
		MessageInfos:      file_gpuhe_proto_msgTypes,
	}.Build()
	File_gpuhe_proto = out.File
	file_gpuhe_proto_goTypes = nil
	file_gpuhe_proto_depIdxs = nil
}
